### ISSUE TITLE
Meetup no ⬆️ QuintoAndar

### ISSUE THREAD

**Issue by fernandrone** [Cloud-Native-BR/meetups#11]
Fala gente! Acabamos de nos mudar pra um escritório novo na Vila Madalena e estamos fechando o calendário de meetups pra esse trimestre, bora levar um evento pra lá?

* Temos um lounge com palco e projetor para até 100 pessoas.
* Conseguimos providenciar comes e bebes.
* Temos interesse em apresentar uma palestra, ainda a decidir :)

Vou me informar sobre o estacionamento.

**Comment by jhonatanmorais** [comment]
Boa @fbcbarbosa! Teria disponibilidade para qual data em fevereiro? @duboc tem algum agendado para fevereiro?

**Comment by fernandrone** [comment]
Dia 6, 20 ou 27 de fevereiro temos disponibilidade @jhonatanmorais!

**Comment by rikatz** [comment]
Vamos criar um calendário no Google Calendar que seja compartilhável, ai da pra ver quando já temos meetups tb :)

**Comment by rikatz** [comment]
Acho que dia 06 fica muito em cima para conseguirmos palestras adicionais (e muito próximo do anterior), sou mais favorável a dia 20 ou 27.

20 estarei em Recife (no Meetup de lá inclusive :P ) mas a data que for melhor para vocês já reservamos na agenda.

**Comment by fernandrone** [comment]
Por mim pode ser. Dia 26 será Quarta-feira de Cinzas... aí dia 27 fazemos o Meetup pro pessoal se curar da ressaca do Carnaval :)

**Comment by rikatz** [comment]
Putz, verdade. Tinha esquecido do feriado

@duboc @yagonobre @jhonatanmorais WDYT?

**Comment by fernandrone** [comment]
É, conversamos internamente e também achamos que pode ser meio ruim depois do carnaval, mas pode ser dia 20.

**Comment by rikatz** [comment]
Beleza, deixei reservado dia 20/02 aqui.

Só me preocupa que Vila Madalena, blocos de rua, carnaval, talvez o @yagonobre pare no meio do caminho...

Vou aguardar o OK do restante do pessoal, já deixei o evento pré criado na agenda

**Comment by fernandrone** [comment]
Blz @rikatz ! Avisa quando pudermos confirmar pra reservar nosso espaço aqui.

Quanto a estacionamento, temos estacionamento (pago) no prédio mas só até ás 19h :/ porém tem vários outros na região :)

https://www.google.com/maps/search/estacionamento/@-23.5542738,-46.6923608,17z/data=!3m1!4b1

Se precisar de mais algo avisa!

**Comment by rikatz** [comment]
Pra mim está reservado, como não estarei ai aguardo um LGTM de alguma outra pessoa pra auxiliar na organização :)

@yagonobre @duboc @jhonatanmorais algum de vcs estará por aqui? Viável essa data?

**Comment by yagonobre** [comment]
Eu consigo ir

**Comment by duboc** [comment]
Dia 27 ok pra mim. Vou estar presente e ajudando!

**Comment by rikatz** [comment]
@duboc pelo que entendi a data proposta é dia 20/02, pois 27/02 é pós carnaval.

Vou criar o Meetup lá e se acharem que deve ser alterado avisem.

**Comment by rikatz** [comment]
Evento criado como rascunho: https://www.meetup.com/pt-BR/Cloud-Native-Sao-Paulo/events/268235456/

Aguardando só a confirmação da data

**Comment by rikatz** [comment]
@fbcbarbosa publicando pro dia 20/02/2020 e fechando

@yagonobre como eu estarei fora e não sei se Duboc estará por aqui tb, vc e o @jhonatanmorais tocam esse :)

**Comment by rikatz** [comment]
https://www.meetup.com/pt-BR/Cloud-Native-Sao-Paulo/events/268235456

**Comment by fernandrone** [comment]
Opa, posto que infelizmente tivemos que cancelar por indisponibilidade do local, vamos reabrir a mesma issue para facilitar? Posso ir atrás de algumas datas mais pra frente, tipo maio ou junho, de acordo com o calendário de vocês :+1:

**Comment by jhonatanmorais** [comment]
Pode ser @fernandrone! Reabra issue com uma nova proposta de data e vamos em frente.

**Comment by fernandrone** [comment]
Opa, @jhonatanmorais @rikatz @yagonobre @duboc não tenho permissão de reabrir a issue, só criando uma nova (e acho que faz mais sentido reabrir essa?).

Pelo que to vendo vocês já tem evento pra abril e maio, não é? Podemos fazer em junho, certamente teremos data. Mas se quiserem uma data mais cedo, posso conseguir, só dizer o mês :slightly_smiling_face:

**Comment by rikatz** [comment]
Fechar, quando tudo voltar ao normal a gente reabre :D
