### ISSUE TITLE
Meetup na Pismo

### ISSUE THREAD

**Issue by andrleite** [Cloud-Native-BR/meetups#14]
## Cidade Sao Paulo
Fala galera blza? Estamos de escritorio novo proximo a estacao de trem vila olimpia e queremos disponibilizar nosso espaço para um meetup, data vamos deixar em aberto para discutirmos aqui na issue. segue as infos
* Data sugerida: **TDB**
* Nome da empresa/local: **[Pismo](http://pismo.io)**
* Endereço do evento: **Av. Engenheiro Luís Carlos Berrini, 105 (berrini one)**
* Quantidade de pessoas que cabem no local: **50**
* A empresa tem interesse em apresentar alguma palestra técnica relacionada a CNCF, Kubernetes, etc durante o evento? **SIM** tema a definir
* Facilities: Projetor? Gravação? Microfone? Etc  **Projetor**
* Tem vagas abertas? Quer que seja anunciado durante o evento também? :) **Sim**
* A empresa poderá fornecer comes e bebes ou fica por conta da organização do Meetup? **Empresa fornece**Cerveja inclui? **SIM** 
* Alguma regra de vestimenta? (ex.: Pode bermuda, não pode chinelo, etc). **NAO**
* Dados necessários para entrada de pessoas no local? **Nome e CPF**

**Comment by yagonobre** [comment]
Boa @andrleite, só definir a data e a gente marca!

**Comment by duboc** [comment]
Vamos deixar o issue aberto até ter a definição a data e depois criamos a url no meetup e postamos aqui.

O que acham?

**Comment by andrleite** [comment]
Como ja temos em fev e marco, imagino que seria em abril, pensei em 14 ou 16. O que acham? Ai eu sugiro essa data aqui. Poderia rolar um resumo da kubecon tb.

**Comment by yagonobre** [comment]
Por mim blz!

**Comment by duboc** [comment]
Por mim qualquer uma das duas datas funciona. 

Confirma a data e a gente já cria a página.

**Comment by rikatz** [comment]
@yagonobre @duboc vamos fazer o Meetupao nessa data? Podemos sugerir 14/Abril que é a Terça em Dobro da Pizza em todos os estados, ai a galera consegue se virar com a Domino's nos outros lugares também. O que acham?

/cc @amioranza @neuhauss @gomex @lsca

**Comment by amioranza** [comment]
Pra mim funciona legal essa data.

**Comment by neuhauss** [comment]
Por mim fechado tbm 

> Em 31 de jan de 2020, à(s) 14:03, A. Mioranza <notifications@github.com> escreveu:
> 
> ﻿Pra mim funciona legal essa data.
>

**Comment by rikatz** [comment]
Beleza então :dagger: 

@andrleite iremos fazer o meetupao ai na Pismo. O que vai ser o Meetupao?

Um Meetup em que teremos uma abertura simultânea com outros meetups que ocorrerão em paralelo (Porto Alegre e Brasília já confirmados), provavelmente com alguém de fora que iremos começar a sondar (fazendo via Zoom de casa), depois mais 2 palestras locais e um fechamento geral se rolar :D

Cada um resolve a sua parte de pizza e cerveja, divulgação a gente faz geralzona :D

Rola fazermos uma vídeo daí, certo?

**Comment by andrleite** [comment]
Boa podemos fechar dia 14 mesmo. 
Entao da para gravarmos com zoom. Fizemos um experimento ontem, nao é a melhor forma mais da pra rolar.

**Comment by rikatz** [comment]
Fechar aqui, quando essa pandemia acabar a gente remarca tudo
