### ISSUE TITLE
Meetup Accenture

### ISSUE THREAD

**Issue by jmaciel33** [Cloud-Native-BR/meetups#15]
## Cidade São Paulo
* Data sugerida: **Abril**
* Nome da empresa/local: **Accenture - Rua Alexandre Dumas, 2051**
* Endereço do evento: **Rua Alexandre Dumas, 2051**
* Quantidade de pessoas que cabem no local: **Até 80 Pessoas.**
* A empresa tem interesse em apresentar alguma palestra técnica relacionada a CNCF, Kubernetes, etc durante o evento? **Sim, tema a definir**
* Facilities: 
Projetor? **Sim** 
Gravação? **Não**
Microfone? **Sim**
* Tem vagas abertas? Quer que seja anunciado durante o evento também? :) **TBD**
* A empresa poderá fornecer comes e bebes ou fica por conta da organização do Meetup? **Sim** Cerveja inclui? **TBD**
* Alguma regra de vestimenta? (ex.: Pode bermuda, não pode chinelo, etc). **Pode bermuda, não pode chinelo.**
* Dados necessários para entrada de pessoas no local?  **Nome, CPF, RG**

**Comment by duboc** [comment]
Isso aqui tá ficando movimentado hein! 

@jmaciel33 viu que já temos alguns meetups marcados no calendário? Qual seria sua pretensão com a data?

**Comment by yagonobre** [comment]
O ideal seria fazer em Maio, dado que a gente vai fazer o da pismo no meio de abril

**Comment by jmaciel33** [comment]
@duboc Sim, eu vi, gostaríamos de fazer no mês de março/abril, mas não tinha visto a issue da Pismo.

Estamos com uma iniciativa na empresa com meetups e eventos, para uma conversa e mostrarmos para comunidade o que estamos fazendo e nosso espaço, inicialmente estávamos com ideia de ser host do CNCF em março/abril.

Agora agenda seria a partir de maio, certo?

**Comment by rikatz** [comment]
@jmaciel33 sim, acaba que ficou em Maio. FIFO :) Por isso tinha te comentado pra abrir a issue logo ;) 

Podemos tentar Maio ai?

**Comment by jmaciel33** [comment]
Sim, claro!

Vou verificar internamente a disponibilidade, mas acho que rola sim!

**Comment by jmaciel33** [comment]
Pessoal, bom dia

Tudo bem?

Poderíamos agendar para a segunda quinzena de maio?
Quais seriam as melhores datas para vocês?

**Comment by rikatz** [comment]
Pode ser sim. A sugestão é sempre ser de 3a feira que a pizza da Dominos é em Dobro :)

Teremos um meetup dia 14/Abril, logo uma distância de 1 mês, 1 mês e pouco fica muito bom :D

**Comment by jmaciel33** [comment]
@rikatz , 

12/05 ou 19/05?

**Comment by rikatz** [comment]
Fechar aqui, quando essa pandemia acabar a gente remarca tudo
