### ISSUE TITLE
Meetup iti Itaú 

### ISSUE THREAD

**Issue by s4rd1nh4** [Cloud-Native-BR/meetups#17]
## São Paulo 
* Data sugerida: Junho
* Nome da empresa/local: iti Itaú 
* Endereço do evento: R. Volkswagen, 1 - Jabaquara, São Paulo - SP, 04344-020. 
* Quantidade de pessoas que cabem no local: 150
* A empresa tem interesse em apresentar alguma palestra técnica relacionada a CNCF, Kubernetes, etc durante o evento? Sim, a definir. 
* Facilities: Projetor? Sim. Gravação? Não. Microfone? Sim. 
* Tem vagas abertas? Quer que seja anunciado durante o evento também? :) Sim. 
* A empresa poderá fornecer comes e bebes ou fica por conta da organização do Meetup? SimCerveja inclui? TBD. 
* Alguma regra de vestimenta? Pode bermuda, não pode chinelo. 
* Dados necessários para entrada de pessoas no local?   Nome, CPF e RG.

**Comment by yagonobre** [comment]
Boa! Quando tiver a data a gente marca o evento.

**Comment by rikatz** [comment]
Fechar aqui, quando essa pandemia acabar a gente remarca tudo
