### ISSUE TITLE
Meetup na Ame

### ISSUE THREAD

**Issue by jonnyken** [Cloud-Native-BR/meetups#9]
Olá pessoal!

Venho convidar o pessoal do Cloud Native BR para realizar um Meetup na Ame Digital. Acabamos de abrir nossa agenda de eventos para o primeiro trimestre e contamos com a participação de vocês em nossa empresa!

Valeu!

**Comment by duboc** [comment]
Opa!  Vamos organizar sim! 

- Qual é o tamanho do auditório? 
- A Ame Digital pretende contribuir com alguma palestra sobre o assunto do Meetup? 
- A Ame Digital consegue providenciar comes e bebes para os participantes? 
- Existe estacionamento por perto? Até que horas o estacionamento permanece aberto?

**Comment by jonnyken** [comment]
- O auditório cabe umas 60 pessoas (mas num Meetup de Elixir entrou umas 100 pessoas rs).
- Posso verificar aqui se alguém tem algum projeto legal que queira falar.
- Sim. Comes, bebes e camiseta :)
- A maioria das pessoas deixam no estacionamento do Shopping Vila Olímpia que é na frente do prédio e é mais barato. Aqui fica do lado da estação Vila Olimpia da CPTM.
- Tem algumas fotos de Meetups anteriores em https://www.amedigital.com/eventos

**Comment by rikatz** [comment]
@jonnyken vamos deixar pré agendado para a segunda quinzena de março? Lembrando que à partir de dia 26 acho que um pessoal estará fora para o Kubecon :)

Se deixarmos já para algum dia na semana de 16 a 20 acho que fica ideal.

Mais alguém?

**Comment by jonnyken** [comment]
Deixei reservado aqui para o dia 17/03!

Inclusive dia 18/03 teremos Meetups do pessoal do NoSQL SP  e 19/03 do pessoal do Scrum SP. Estão todos convidados! :D

**Comment by rikatz** [comment]
Deixei pré reservado na agenda como dia 17/03.

Vamos ver se o restante da galera consegue da o OK :)

E gostei da ideia da camiseta :P

**Comment by yagonobre** [comment]
Muito bom!

**Comment by duboc** [comment]
Ok por mim. Vamos executar o evento no dia proposto!

**Comment by jonnyken** [comment]
SHOW!! :D 
Qq é só entrar em contato por aqui :D 
Valeu!

**Comment by rikatz** [comment]
Rascunho criado - https://www.meetup.com/pt-BR/Cloud-Native-Sao-Paulo/events/268241832/

@jonnyken se tiver alguém que queira falar sobre algo Cloud Native me avisa nessa issue pra reservarmos o slot :)

Vou fechar a issue mas pode comentar por aqui. Assim que passar o meetup 16 eu publico o 17 :)

**Comment by jonnyken** [comment]
Ah!!! Se a inscrição deixar muita gente de fora, a gente pode transmitir o evento ao vivo (mas a gente divulga só algumas horas antes para não esvaziar o evento)
um que a gente transmitiu para vocês darem uma olhada
https://youtu.be/G_v9DWUK8ig?t=1063
